---
apiVersion: v1
kind: Secret
metadata:
  name: dryrun-photo-generator-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/keynote-demo/dryrun-photo-generator-gitops
